DROP TABLE View_Event_Information CASCADE CONSTRAINTS;
DROP TABLE View_Tag_Information CASCADE CONSTRAINTS;
DROP TABLE View_Photo_Information CASCADE CONSTRAINTS;
DROP TABLE View_Are_Friends CASCADE CONSTRAINTS;
DROP TABLE View_User_Information CASCADE CONSTRAINTS;
DROP TABLE Current_City_F CASCADE CONSTRAINTS;
DROP TABLE Hometown_City_F CASCADE CONSTRAINTS;
DROP TABLE Institution_F CASCADE CONSTRAINTS;