DROP TABLE Friends;
DROP TABLE User_Current_Cities;
DROP TABLE User_Hometown_Cities;
DROP TABLE Participants;
DROP TABLE Tags;
DROP TABLE Photos CASCADE CONSTRAINTS;
DROP TABLE Albums CASCADE CONSTRAINTS;
DROP TABLE User_Events;
DROP TABLE Education;
DROP TABLE Programs;
DROP TABLE Messages;
DROP TABLE Cities;
DROP TABLE Users CASCADE CONSTRAINTS;

DROP SEQUENCE Cities_seq;
DROP SEQUENCE Programs_seq;